### ISSUE TITLE
Error: Unrecognized input format

### ISSUE THREAD

**Issue by baigmirzasarwar** [AntonelliLab/raxmlGUI#120]
Autogenerated report:
```json
{
  "message": "Error parsing file C:\\Users\\Dell-PC\\Desktop\\Coronavirus\\21_CoV_H+P+B+C+S.mas: Unrecognized input format",
  "name": "Error",
  "stack": "Error: Error parsing file C:/Users/Dell-PC/Desktop/Coronavirus/21_CoV_H+P+B+C+S.mas: Unrecognized input format\n    at Interface.<anonymous> (C:/Users/Dell-PC/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:8441)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 123 -p 123 -N 1000 -m GTRGAMMA -O -n 21_CoV_H+P+B+C+S.tre -s \"C:\\Users\\Dell-PC\\Desktop\\Coronavirus\\RAxML_21_CoV_H+P+B+C+S_concat.txt\" -w \"C:\\Users\\Dell-PC\\Desktop\\Coronavirus\"",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.10
Electron 7.2.4
win32 10.0.18362
Locale: en-US

**Comment by jtklein** [comment]
The format of the alignment you were trying to load is not supported by the RAxML-GUI at this point. Currently, only fasta and phyllip formatted files are supported.

**Comment by jtklein** [comment]
I will add a more detailed error message dialog to the GUI for this case.

**Comment by baigmirzasarwar** [comment]
Thank you for your kind response.
*With Warm Regards,*
*Mirza Sarwar Baig (Ph.D.)*
*Post Doctoral Research Associate*
*(Indian Council of Medical Research) *
*Lab No. 310B, **Department of Molecular Medicine*
*Jamia Hamdard, New Delhi-110062*
*Mob No. +91-9990612416 / +91-9582633247*
*Email ID- mirzasbaig@jamiahamdard.ac.in <drkamalahmad@jamiahamdard.ac.in>*
https://scholar.google.co.in/citations?hl=en&user=jZuAUrUAAAAJ
