### ISSUE TITLE
Restyle light themed citation div

### ISSUE THREAD

**Issue by jtklein** [AntonelliLab/raxmlGUI#127]
The text in the citation window is black on a black field in the light theme. In the dark mode it is white on black. So I think the background div should switch to white in the light theme.

<img width="690" alt="Bildschirmfoto 2020-07-13 um 22 12 43" src="https://user-images.githubusercontent.com/17345891/87416094-7e3bbb00-c5ce-11ea-9cd1-f85baeddfba1.png">

**Comment by dsilvestro** [comment]
I think we should also change the default tab to plain text and have from left to right: plaint text, Endnote, bibtex

**Comment by jtklein** [comment]
> I think we should also change the default tab to plain text and have from left to right: plaint text, Endnote, bibtex

Done
