### ISSUE TITLE
Error: multistate character set used invalid

### ISSUE THREAD

**Issue by starsareintherose** [AntonelliLab/raxmlGUI#131]
Autogenerated report:
```json
{
  "message": "Exited with code 4294967295. Check console output for more information.",
  "name": "Error",
  "stack": "Error: Exited with code 4294967295. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/月季花中的星辰/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:14184)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 123 -p 123 -N 1000 -m MULTIGAMMA -K GTR -k -O -n mor_4.tre -s \"F:\\snail\\paper\\writing\\liu\\phylo\\20200731\\ML\\mor.fas\" -w \"F:\\snail\\paper\\writing\\liu\\phylo\\20200731\\ML\"",
  "stdout": "[4060 more characters]...must be used in the order they are available, i.e.\r\n0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V\r\nYou are using the following characters: \r\n1 2 3 4 \r\n"
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.14
Electron 7.2.4
win32 10.0.18362
Locale: zh-CN

**Comment by jtklein** [comment]
Hello,
If I am not mistaken, the error means that you were trying to make an analysis with a multistate alignment and did not use the correct states. If you have multistate data it needs to start with 0.
In other words, instead of having the characters 1,2,3,4 in your alignment you should have 0,1,2,3.
Hope that resolves the error for you.

**Comment by jtklein** [comment]
But I think we should have a case for catching this error before it occurs.

**Comment by starsareintherose** [comment]
> Hello,
> If I am not mistaken, the error means that you were trying to make an analysis with a multistate alignment and did not use the correct states. If you have multistate data it needs to start with 0.
> In other words, instead of having the characters 1,2,3,4 in your alignment you should have 0,1,2,3.
> Hope that resolves the error for you.

Thanks, it's delt. Best wishes, Guoyi
