### ISSUE TITLE
Error: Less than 4 sequences

### ISSUE THREAD

**Issue by GaryMyrmecology** [AntonelliLab/raxmlGUI#162]
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Exited with code 1. Check console output for more information.",
  "stack": "Error: Exited with code 1. Check console output for more information.\n    at ChildProcess.<anonymous> (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:19978)"
}
```

Active state:
```json
{
  "command": "raxml-ng --all --msa /Users/zuzuthegogo/Desktop/Contig_0HA_2020.TXT --model GTR --prefix /Users/zuzuthegogo/Desktop/Contig_0HA_2 --seed 123 --bs-metric tbe --tree rand{1} --bs-trees 100",
  "stdout": "[1168 more characters]...hegogo/Desktop/Contig_0HA_2020.TXT\n[00:00:00] Loaded alignment with 1 taxa and 35816 sites\n\nERROR: Your alignment contains less than 4 sequences! \n\nERROR: Alignment check failed (see details above)!\n\n"
}
```

---

Process: renderer
raxmlGUI 2.0.0
Electron 10.1.1
darwin 19.6.0
Locale: en-US

**Comment by dsilvestro** [comment]
Thank you @GaryMyrmecology for reporting the problem. According to the RAxML error message the alignment contains fewer than 4 taxa, which is not allowed by the program. Is that the case?

**Comment by jtklein** [comment]
Maybe we can turn this into an error case that does not show the „Report to GitHub“ option, as it is something the users should fix.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AntonelliLab/raxmlGUI/issues/162#issuecomment-704294038",
"url": "https://github.com/AntonelliLab/raxmlGUI/issues/162#issuecomment-704294038",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by GaryMyrmecology** [comment]
There are 62 taxa/individual sequences

**Comment by danieledler** [comment]
@GaryMyrmecology, as raxmlGUI "Loaded alignment with 1 taxa and 35816 sites", probably there is a formatting or parsing issue. Are you able to share the input file?
