### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cdp-rna** [AntonelliLab/raxmlGUI#172]
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Exited with code 1. Check console output for more information.",
  "stack": "Error: Exited with code 1. Check console output for more information.\n    at ChildProcess.<anonymous> (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:19978)"
}
```

Active state:
```json
{
  "command": "raxml-ng --all --msa /Users/christinapalka/RNA_clustering_scripts/201202_500memb_fasta_1/201202_500_1.phy --model GTR --prefix /Users/christinapalka/Desktop/201202_500_1 --seed 123 --bs-metric tbe --tree rand{1} --bs-trees 100",
  "stdout": "[648 more characters]...noit Morel, David Posada, \n              Alexandros Stamatakis.\nLatest version: https://github.com/ddarriba/modeltest\n--------------------------------------------------------------------------------\n\n"
}
```

---

Process: renderer
raxmlGUI 2.0.0
Electron 10.1.1
darwin 18.7.0
Locale: en-US

**Comment by danieledler** [comment]
Hi @cdp-rna and thanks for reporting the issue! Unfortunately it's not clear from the current output what the error is, can you share a screenshot showing more of the console message? And does it happen when you press "Optimize" or when does it happen?

**Comment by cdp-rna** [comment]
Hi sorry about the delay in the response. I get the errors shown in the attached  screenshot when I try to run the attached 201202.phy file. Its weird because I can run another .phy file (convertedmsa.txt) just fine....

SCREENSHOT OF ERROR:
<img width="580" alt="Screen Shot 2020-12-05 at 1 26 06 PM" src="https://user-images.githubusercontent.com/57539905/101265718-786d8000-36fd-11eb-875c-15d85d607c12.png">

FILE THAT RUNS: 
[convertedmsa.txt](https://github.com/AntonelliLab/raxmlGUI/files/5647889/convertedmsa.txt)

FILE THAT DOES NOT RUN: 
[201202.txt](https://github.com/AntonelliLab/raxmlGUI/files/5647892/201202.txt)

**Comment by cdp-rna** [comment]
I also get an error when I try to optimize.
