### ISSUE TITLE
Error: Exited with code 3221225781

### ISSUE THREAD

**Issue by nadiavh2** [AntonelliLab/raxmlGUI#182]
Hello, raxmlGUI marks me this error when optimize

Autogenerated report:
```json
{
  "name": "Error",
  "message": "Exited with code 3221225781. Check console output for more information.",
  "stack": "Error: Exited with code 3221225781. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/NadiaV Herrera/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:21493)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-AVX2.exe -T 2 -f a -x 612253 -p 612253 -N 100 -m GTRGAMMA -O -n COOLIA-LSUAlineamientoMUSCLE.tre -s \"C:\\Analisismolecular\\PRUEBAS\\MAXIMA VEROSIMILITUD\\COOLIA\\COOLIA-LSUAlineamientoMUSCLE.fas\" -w \"C:\\Analisismolecular\\PRUEBAS\\MAXIMA VEROSIMILITUD\\COOLIA\"",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.3
Electron 12.0.2
win32 10.0.19042
Locale: es

**Comment by danieledler** [comment]
Hi @nadiavh2 and thanks for providing this feedback!

As you use Windows, maybe there is an issue with the new Windows binary for ModelTest-NG added in the latest version. Can you please try download and run the previous version instead ([raxmlGUI-Setup-2.0.2.exe](https://github.com/AntonelliLab/raxmlGUI/releases/tag/v2.0.2)), and update us on how it works?

Thanks!

**Comment by jtklein** [comment]
Hello @nadiavh2, I believe I have fixed this error. Can you please install this newer version and let me know if the error happens again, or if everything is fine now.
https://github.com/AntonelliLab/raxmlGUI/releases/download/v2.0.4/raxmlGUI-Setup-2.0.4.exe

**Comment by nadiavh2** [comment]
Thanks for the new version! I was able to run the analysis of modeltets.
When I try to run the ML analysis, I do not see others models such as TIM1 + I, I only have the GTR, GTRGMMA and GTRGMMAI versions.
In the article mentioned that only the mac and linUx versions do it. Could it be a new problem in the program?

**Comment by jtklein** [comment]
Thank you for testing! Happy it is fixed.
On Windows you can only choose to use RAxML for analysis. So yes, only those models you described are available for you. RAxML-NG which provides more model choice is not available on Windows currently.
