### ISSUE TITLE
Change from generic to specific error message for identical name taxa

### ISSUE THREAD

**Issue by Inom92** [AntonelliLab/raxmlGUI#193]
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Exited with code 4294967295. Check console output for more information.",
  "stack": "Error: Exited with code 4294967295. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/ИНОМ/AppData/Local/Programs/raxmlgui/resources/app.asar/build/electron.js:1:21493)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 962144 -p 962144 -N 1000 -m GTRGAMMA -O -n psbA-trnH_1.tre -s \"D:\\Hedyasrum L\\Hedysarum yangi\\Maqola\\Phylogeny\\Genes\\psbA-trnH\\psbA-trnH.fas\" -w \"D:\\Hedyasrum L\\Hedysarum yangi\\Maqola\\Phylogeny\\Genes\\psbA-trnH\\RAxML\"",
  "stdout": "[13813 more characters]...re identical, they are both called Hedysarum\r\nSequence names of taxon 19 and 20 are identical, they are both called Hedysarum\r\nERROR: Found 171 taxa that had equal names in the alignment, exiting...\r\n"
}
```

---

Process: renderer
raxmlGUI 2.0.5
Electron 12.0.7
win32 10.0.10586
Locale: ru

**Comment by danieledler** [comment]
Hi @Inom92, thanks for reporting the issue!

As you may have seen, the problem is this:

> Sequence names of taxon 19 and 20 are identical, they are both called Hedysarum
> ERROR: Found 171 taxa that had equal names in the alignment, exiting...

We should try to make this error message more clear to the user, but if the issue is the parsing of sequence names, that they are unique in the file but the unique part is missed, can you please share the input file?

**Comment by jtklein** [comment]
Hello @Inom92,
we actually have made some changes to react to this error more clearer in the version you used. Somehow your alignment file must have slipped through our recognition mechanism for this very error.
In order for us to understand why your alignment file failed, can you share with us this alignment file?
