### ISSUE TITLE
ModelTest button does not fit in the tile

### ISSUE THREAD

**Issue by dsilvestro** [AntonelliLab/raxmlGUI#212]
![Screen Shot 2021-09-30 at 10 56 18](https://user-images.githubusercontent.com/7657285/135429368-0ff289a1-42fa-4fe1-8439-136eb0d89b5e.png)

**Comment by jtklein** [comment]
This should be already fixed in the latest version. Can you download version 2.0.6 from the draft release and check that this error is gone?

**Comment by dsilvestro** [comment]
yep that's fixed thanks!
