### ISSUE TITLE
Remove alignment button hidden when alignment name too long

### ISSUE THREAD

**Issue by dsilvestro** [AntonelliLab/raxmlGUI#213]

**Comment by jtklein** [comment]
What do you mean with that?
We do have a button to remove an alignment. It is top right on the alignment card.

**Comment by dsilvestro** [comment]
<img width="564" alt="Screen Shot 2021-10-01 at 12 21 51" src="https://user-images.githubusercontent.com/7657285/135604753-7a6f603b-2f78-4a8c-ae49-50bfb33403ac.png">
 You are right, the problem only occurs with very long (too long) file names
