### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by sureshpanthee** [AntonelliLab/raxmlGUI#214]
Hi,
I tried to download the installation file for windows but when I attempt to download it from the link below, it gives 404 page not found error. Can you please help?

Thanks

Suresh
https://github.com/AntonelliLab/raxmlGUI/releases/download/v2.0.5/raxmlGUI-Setup-2.0.5.exe

**Comment by jtklein** [comment]
Hello,
version 2.0.5 is temporarily unavailable, however, we published a newer version. You can find the installation file here:
https://github.com/AntonelliLab/raxmlGUI/releases/download/v2.0.6/raxmlGUI-Setup-2.0.6.exe
