### ISSUE TITLE
apparently superfluous option

### ISSUE THREAD

**Issue by dsilvestro** [AntonelliLab/raxmlGUI#22]
when running "ML search" the "Combined output" does not do anything (and apparently neither it did in v.1): we can remove it

**Comment by boronian** [comment]
If I remember correctly it was meant to produce a combined output file for all those ML trees...: If you do 100 ML searches you will get 100 files with one tree each... The idea was to get one file with those 100 trees instead... Not sure if it ever worked to be honest, though.
