### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cmtribull** [AntonelliLab/raxmlGUI#220]
Hello, trying to run a mixed data files of molecular and morphological data - is that not allowed? Please see below

Autogenerated report:
```json
{
  "name": "Error",
  "message": "Invalid alignment: sequences must be of same data type, but found [mixed,nucleotide,multistate].",
  "stack": "Error: Invalid alignment: sequences must be of same data type, but found [mixed,nucleotide,multistate].\n    at typecheckAlignment (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:10215)\n    at Interface.<anonymous> (/Applications/raxmlGUI.app/Contents/Resources/app.asar/build/electron.js:1:16472)"
}
```

Active state:
```json
{
  "command": "raxml-ng --all --msa /Users/carly/Downloads/RAxML_BayesianConversion_1_concat.txt --model --prefix /Users/carly/Downloads/BayesianConversion_1 --seed 626494 --bs-metric tbe --tree rand{1} --bs-trees 100",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.6
Electron 13.5.1
darwin 20.6.0
Locale: en-US

**Comment by danieledler** [comment]
Hi @cmtribull, thanks for reporting the issue!

Mixed data should be supported, just requiring a partition as additional data, specifying the type for each site. However, it seems that sequence two and three are of a single type nucleotide and multistate respectively. Can you maybe share the data?
