### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ChetanGaonkar** [AntonelliLab/raxmlGUI#226]
Autogenerated report:
```json
{
  "name": "Error",
  "message": "Error trying to execute raxml binary '/tmp/.mount_raxmlGw2KeKS/resources/static/bin/raxml-ng': spawn /tmp/.mount_raxmlGw2KeKS/resources/static/bin/raxml-ng EACCES",
  "stack": "Error: Error trying to execute raxml binary '/tmp/.mount_raxmlGw2KeKS/resources/static/bin/raxml-ng': spawn /tmp/.mount_raxmlGw2KeKS/resources/static/bin/raxml-ng EACCES\n    at IpcMainImpl.<anonymous> (/tmp/.mount_raxmlGw2KeKS/resources/app.asar/build/electron.js:1:21843)"
}
```

Active state:
```json
{
  "command": "raxml-ng --all --msa /home/campbelllab/synology/transcriptome_data/metabarcoding/HAB_paper/hab_v4_dec21.txt --model GTR+I --prefix /home/campbelllab/synology/transcriptome_data/metabarcoding/HAB_paper/hab_v4_dec21 --seed 128646 --bs-metric tbe --tree rand{10} --bs-trees 1000",
  "stdout": ""
}
```

---

Process: renderer
raxmlGUI 2.0.6
Electron 13.5.1
linux 5.8.0-50-generic
Locale: en-US

**Comment by danieledler** [comment]
Hi @ChetanGaonkar and thanks for reporting the issue.

The `spawn /tmp/.mount_raxmlGw2KeKS/resources/static/bin/raxml-ng EACCES` part means that raxmlGUI doesn't have access to the directory. From what I have found it seems to be a [sandboxing issue](https://docs.appimage.org/user-guide/troubleshooting/electron-sandboxing.html) with Debian:

> AppImages based on Electron require the kernel to be configured in a certain way to allow for its sandboxing to work as intended (specifically, the kernel needs to be allowed to provide “unprivileged namespaces”). Many distributions come with this configured out of the box (like Ubuntu for instance), but some do not (for example Debian).

It also seems that this was [solved in later versions](https://github.com/laurent22/joplin/issues/2246#issuecomment-808570233):

> If you run the Debian 10 (Buster) stable kernel 4.19 you will still be affected by this issue.
If you upgrade to Bullseye (which will become the new stable release in a few months) you will not be affected.
If you install the 5.10 kernel from Buster-backports you will not be affected.

As you have kernel 5.8, this seems to be a likely cause of the problem. Are you able to upgrade the kernel or Debian?

**Comment by ChetanGaonkar** [comment]
Dear Daniel,

I got a popup saying new version is available so I upgraded.
The older version dont have any issue as I have two PC one with older and
other with upgraded version.
I ran the phylogenies on the older one and they work well.
Thank you,
Chetan

**Comment by danieledler** [comment]
Ok, in raxmlGUI 2.0.6 there was a new version of raxml-ng added, maybe @jtklein knows something about this?

**Comment by danieledler** [comment]
In the meantime @ChetanGaonkar, if you can upgrade the kernel pleasy try that. That will help us if more get the same problem.

**Comment by ChetanGaonkar** [comment]
I am not 100% sure how to upgrade the kernel.
Will look into it and try again
Chetan

**Comment by thauffe** [comment]
I'm having the same issue. My kernel version is 5.10-98.
I checked that unprivileged namespaces [are enabled ](https://docs.appimage.org/user-guide/troubleshooting/electron-sandboxing.html)by my distribution and they are.

Keep up the good work!

**Comment by thauffe** [comment]
Hi, Version 2.0.5 works.

I run a `sudo .\raxmlGUI-2.0.5.AppImage --no-sandbox` with version 2.0.5 and 2.0.6 and attach the output as text file. There are some more detailed messages beginning in line 85 of v205.txt:

```
ALIGNMENT_SELECTED {
  canceled: false,
  filePaths: [ '/home/.../Pota_cytb.fas' ]
}
Parse alignment /home/.../Pota_cytb.fas
error Error: Command failed: /tmp/.mount_raxmlGTZ1NCf/resources/static/bin/readal -in /home/.../Pota_cytb.fas -type -format
/bin/sh: line 1: /tmp/.mount_raxmlGTZ1NCf/resources/static/bin/readal: Permission denied

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  killed: false,
  code: 126,
  signal: null,
  cmd: '/tmp/.mount_raxmlGTZ1NCf/resources/static/bin/readal -in /home/.../Pota_cytb.fas -type -format',
  stdout: '',
  stderr: '/bin/sh: line 1: /tmp/.mount_raxmlGTZ1NCf/resources/static/bin/readal: Permission denied\n'
}
```
[v205.txt](https://github.com/AntonelliLab/raxmlGUI/files/8097057/v205.txt)
[v206.txt](https://github.com/AntonelliLab/raxmlGUI/files/8097058/v206.txt)

.

**Comment by ChetanGaonkar** [comment]
Hi I had to go back to the older version and ran my phylogenies.
I can send you the version and the log tomorrow if that is ok?
Regards
Chetan

**Comment by danieledler** [comment]
@ChetanGaonkar, we are testing a new version today, hopefully that will solve the issue. Will let you know.

**Comment by danieledler** [comment]
Hi all, we just released v2.0.7 that should fix this Linux issue. You should get it on the automatic update check when raxmlGUI starts. Please try and write if it solves the issue for you!

**Comment by thauffe** [comment]
Great, works in my case. Thank you!

**Comment by ChetanGaonkar** [comment]
Great thanks.
Will check it out too in next few days and keep you updated.
Chetan
