### ISSUE TITLE
Not sure how to input model GTR+I+G4

### ISSUE THREAD

**Issue by Niv94** [AntonelliLab/raxmlGUI#242]
Dear team,

I ran the modeltest for my data and it says I use GTR+I+G4. I am able to enter GTR+I+G as the model but not sure how to ask the program to have 4 distinct gamma categories for G"4". Could you please help?
Thanks in advance.

**Comment by dsilvestro** [comment]
Thank you for bringing this up. Raxml will by default use 4 categories, while raxml-ng allows for a user-determined number of categories (but still use 4 by default). We will make that option available through raxmlGUI asap, but for now you can use the current version as it will use G4.

**Comment by Niv94** [comment]
Thats great. Thanks a lot for your quick assistance.
