### ISSUE TITLE
add HKY, JC etc. models to DNA option

### ISSUE THREAD

**Issue by dsilvestro** [AntonelliLab/raxmlGUI#43]
Add labels JC69, K80, HKY85 to the model selection for a DNA alignment. This will generate the following RAxML commands:

-m GTRGAMMA --­­HKY85
-m GTRGAMMA --­­K80
-m GTRGAMMA --­­JC69

(the default should still be GTRGAMMA)

**Comment by jtklein** [comment]
In raxml these settings, specify that all DNA partitions will evolve under the respective model, 
this overrides all other model specifications for DNA partitions.
In raxml-ng you can set the model directly for each partition. It makes more sense to direct the user to ng if someone wants to use these models.
