### ISSUE TITLE
allow user defined number of bootstrap replicates and runs in ML search

### ISSUE THREAD

**Issue by dsilvestro** [AntonelliLab/raxmlGUI#53]

**Comment by jtklein** [comment]
This was implemented in the original repository, I can copy the fix over.

**Comment by jtklein** [comment]
There are no bootstrap replicates in ML search, afaik. Have added the number os runs selector to this analysis. In the original repository there was also the option for a user defined number of runs.
@dsilvestro feel free to reopen this issue if more work needed

**Comment by dsilvestro** [comment]
good point! I guess I meant just number of runs!
