### ISSUE TITLE
Space in filename not properly escaped

### ISSUE THREAD

**Issue by SDeans0** [AntonelliLab/raxmlGUI#69]
I used an alignment generated by CLC workbench, which allows spaces in object names and doesn't allow you to automatically remove them on output to file. I changed the filename to get this to work, but it might be worth automatically parsing this in the program. Thanks for making such a slick tool though 👍 

Autogenerated report:
```json
{
  "message": "Exited with code 4294967295. Check console output for more information.",
  "name": "Error",
  "stack": "Error: Exited with code 4294967295. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/deanss/AppData/Local/Temp/1SEP9TxxsZxukMPlWZMyTD49Czl/resources/app.asar/build/electron.js:1:11366)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 4 -f a -x 295 -p 358 -N 100 -m PROTGAMMABLOSUM62 -k -n At_mRNA_translations alignment.tre -s E:\\At_mRNA translations alignment.phy -O -w E:\\",
  "stdout": "[9 more characters]...you specified a working directory via \"-w\"\r\nKeep in mind that RAxML only accepts absolute path names, not relative ones!\r\nThe file E:\\At_mRNA you want to open for reading does not exist, exiting ...\r\n"
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.1
Electron 6.0.2
win32 10.0.16299
Locale: en-US

**Comment by dsilvestro** [comment]
Thanks for reporting this issue! We'll fix it ASAP!

**Comment by jtklein** [comment]
Just a note:
I could not reproduce this error on Mac. Maybe it is restricted to Windows only.

**Comment by danieledler** [comment]
The issue should be fixed in the latest version, so please [download](https://antonellilab.github.io/raxmlGUI/) and check that you get it to work too!

**Comment by SDeans0** [comment]
@danieledler Thanks for updating this, the problem is resolved now! :)
