### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xum1** [AntonelliLab/raxmlGUI#70]
Autogenerated report:
```json
{
  "message": "Exited with code 4294967295. Check console output for more information.",
  "name": "Error",
  "stack": "Error: Exited with code 4294967295. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/maonian/AppData/Local/Temp/1SEP9TxxsZxukMPlWZMyTD49Czl/resources/app.asar/build/electron.js:1:11366)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 502 -p 9 -N 500 -m GTRGAMMA -k -n conDcladeITS20181230.tre -s F:\\PhyDe\\Cetrariella\\20191105 Algal ITS ambiguous sites\\conDcladeITS20181230.fas -O -o A_Trebouxia_asymmetrica_AJ249565 -w F:\\PhyDe\\Cetrariella\\20191105 Algal ITS ambiguous sites",
  "stdout": "[28 more characters]...king directory via \"-w\"\r\nKeep in mind that RAxML only accepts absolute path names, not relative ones!\r\nThe file F:\\PhyDe\\Cetrariella\\20191105 you want to open for reading does not exist, exiting ...\r\n"
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.1
Electron 6.0.2
win32 10.0.17763
Locale: en-US

**Comment by jtklein** [comment]
File name with spaces seems to be the issue here as well.

Sent using the WEB.DE mail app

**Comment by xum1** [comment]
Hi, Johannes,

It works when I put everything in ONE folder - alignment fasta files with
the exe application.

Best regards,
Maonian

Johannes Klein <notifications@github.com> 于2019年11月5日周二 下午4:59写道：

**Comment by jtklein** [comment]
Just a note:
I could not reproduce this error on Mac. Maybe it is restricted to Windows only.

**Comment by xum1** [comment]
Yes, I was using a Windows 10 computer.

Johannes Klein <notifications@github.com> 于2019年11月8日周五 下午12:05写道：

**Comment by danieledler** [comment]
@xum1, the space-in-filename issue should be fixed in the latest version, so please [download](https://antonellilab.github.io/raxmlGUI/) and comment again if you still have any issues!
