### ISSUE TITLE
Error: Taxon name too long

### ISSUE THREAD

**Issue by agaballa** [AntonelliLab/raxmlGUI#98]
Autogenerated report:
```json
{
  "message": "Exited with code 4294967295. Check console output for more information.",
  "name": "Error",
  "stack": "Error: Exited with code 4294967295. Check console output for more information.\n    at ChildProcess.<anonymous> (C:/Users/ag67/AppData/Local/Temp/1VwpZXVjlxa71FqF64VsrcyUQeJ/resources/app.asar/build/electron.js:1:12852)"
}
```

Active state:
```json
{
  "command": "raxmlHPC-PTHREADS-SSE3.exe -T 2 -f a -x 123 -p 123 -N 100 -m GTRGAMMA -O -n rpoATalign.tre -s \"C:\\raxmlwork\\rpoATalign.phy\" -w \"C:\\raxmlwork\"",
  "stdout": "[21 more characters]...d a working directory via \"-w\"\r\nKeep in mind that RAxML only accepts absolute path names, not relative ones!\r\nTaxon Name too long at taxon 392, adapt constant nmlngth in\r\naxml.h, current setting 256\r\n"
}
```

---

Process: renderer
raxmlGUI 2.0.0-beta.4
Electron 7.1.7
win32 10.0.17763
Locale: en-US

**Comment by jtklein** [comment]
It seems that RAxML has a limitation on how long a taxon name can be. 256 characters.

In your case name of taxon 392 is too long.

**Comment by jtklein** [comment]
I think we should not shorten the taxon name automatically. Changing the input names may break pipelines or confuse the user. What do you think, @danieledler @dsilvestro ?
I have added a specific error message that tells the user to shorten the name, and the alignment is rejected. I consider this closed.
